Refactor tests

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Integration test (requires firefox)
+# Integration tests (requires firefox)
 
 set -e
 
@@ -8,24 +8,23 @@ cleanup() {
   kill 0 && wait
 }
 
-curl_with_retry() {
-  curl --silent --retry 2 --retry-connrefused --max-time 5 "$@" > /dev/null
-}
-
 trap cleanup EXIT
+
+curl_with_retry() {
+  curl --silent --retry 2 --retry-connrefused --max-time 5 --output /dev/null "$@"
+}
 
 # Start weblink
 bin/weblink --client --server &
-
 # Wait for weblink to be ready
 curl_with_retry http://127.0.0.1:8080/
-
-# Establish connection between the client and server
+# Establish connection between the client and the server
 firefox "http://127.0.0.1:8080/?server=ws://127.0.0.1:8000&batch=2"
-
-# Test that everything works
+# Make multiple requests in parallel through weblink to test everything
 for _ in $(seq 1 3); do
-  (curl_with_retry -px http://127.0.0.1:3128 https://www.google.com/ && echo "SUCCESS" || echo "FAILURE") &
+  (curl_with_retry -px http://127.0.0.1:3128 https://www.google.com/ \
+    && echo "SUCCESS" || echo "FAILURE") &
   pids="$! $pids"
 done
+# shellcheck disable=SC2086
 wait $pids
